### PR TITLE
it is time for the future of ArkadiusTradeTools

### PR DESCRIPTION
**Pull request by DakJaniels**
I have been working on this for a few months now and it is very nice. 
LibAsync integration so I could use ESO-Profiler for UI Load Profiling, without it, Arkadius Trade Tools makes the game hang when profiling. 
LibHistorie, LibChatMessage, LibDebugLogger, LibGuildRoster, LibAsync  are required deps now in this build.

### CODE REVIEW

**Comment by timothymclane** [comment]
Thanks for submitting this PR, @DakJaniels! I haven't had time to devote to ATT for a while, so I'm glad to see some changes out here which pull in some of the newer functionality and libs.

There are **a ton** of changes here, but it looks like a lot of them are formatting (removing parentheses for if checks, reformatting empty functions, etc.). It's going to take me a while to parse through all of this and understand the changes. If you'd go back and revert the changes that are just formatting, that will help keep the PR focused and speed my review along.

Again, thanks for all of your hard work on this! I'm looking forward to seeing how it improves ATT! 👍

**Comment by DakJaniels** [comment]
I will see if I can do that. It might be easier to format the original libhistory branch with my format then to undo the format though.

**Comment by DakJaniels** [comment]
a few new changes are the use of os.date in the time calculations.  zo_getSafeId64Key for retrieving id64s and HashString in ArkadiusTradeToolsSales:AddEvent. because the Id was saving duplicates and negetive id64s, crazy I know.  Let me know if you have any questions or if youd like to discuss over discord you can add me there too, dack  or Dack#3850. some people can't find the first name.

**Comment by DakJaniels** [comment]
closed pull due to it needing another rewrite come update 41. https://www.esoui.com/forums/showthread.php?p=48688#post48688

**Comment by timothymclane** [comment]
As far as I've seen from Sirinsidiator, there won't be any changes to the public API of LibHistoire, so this branch can continue without consuming any of those changes.

**Comment by DakJaniels** [comment]
Nice. I'm still working on things too. Not sure why some items are missing from the data or displaying inaccurate information. Like fore example a purple companion ring will show in the tooltip the price of a blue quality but when you hover over the blue item the pice is for the purple.

**Pull request closed without merging**
